const questionBank = [
    // === HTML (Questions 1-25) ===
    { id: 1, category: "HTML", question: "What does HTML stand for?", options: ["Hyper Text Markup Language", "High Text Markup Language", "Hyper Tabular Markup Language", "Hyperlink and Text Markup Language"], answer: 0 },
    { id: 2, category: "HTML", question: "Who is making the Web standards?", options: ["Mozilla", "Google", "The World Wide Web Consortium (W3C)", "Microsoft"], answer: 2 },
    { id: 3, category: "HTML", question: "Choose the correct HTML element for the largest heading:", options: ["<heading>", "<h6>", "<h1>", "<head>"], answer: 2 },
    { id: 4, category: "HTML", question: "What is the correct HTML element for inserting a line break?", options: ["<br>", "<lb>", "<break>", "<next>"], answer: 0 },
    { id: 5, category: "HTML", question: "What is the correct HTML for creating a hyperlink?", options: ["<a>http://google.com</a>", "<a href='http://google.com'>Google</a>", "<a url='http://google.com'>Google</a>", "<href='http://google.com'>Google</href>"], answer: 1 },
    { id: 6, category: "HTML", question: "Which character is used to indicate an end tag?", options: ["*", "<", "/", "^"], answer: 2 },
    { id: 7, category: "HTML", question: "How can you open a link in a new tab/browser window?", options: ["<a href='url' target='new'>", "<a href='url' target='_blank'>", "<a href='url' new>", "<a href='url' target='_window'>"], answer: 1 },
    { id: 8, category: "HTML", question: "Which of these elements are all <table> elements?", options: ["<table><tr><td>", "<table><head><body>", "<table><tr><tt>", "<thead><body><tr>"], answer: 0 },
    { id: 9, category: "HTML", question: "Inline elements are normally displayed without starting a new line.", options: ["True", "False"], answer: 0 },
    { id: 10, category: "HTML", question: "How can you make a numbered list?", options: ["<ul>", "<ol>", "<dl>", "<list>"], answer: 1 },
    { id: 11, category: "HTML", question: "How can you make a bulleted list?", options: ["<ol>", "<list>", "<ul>", "<dl>"], answer: 2 },
    { id: 12, category: "HTML", question: "What is the correct HTML for making a checkbox?", options: ["<check>", "<input type='checkbox'>", "<checkbox>", "<input type='check'>"], answer: 1 },
    { id: 13, category: "HTML", question: "What is the correct HTML for making a text input area?", options: ["<input type='textfield'>", "<input type='text'>", "<textinput>", "<textarea>"], answer: 1 },
    { id: 14, category: "HTML", question: "What is the correct HTML for inserting an image?", options: ["<img alt='MyImage'>image.gif</img>", "<image src='image.gif' alt='MyImage'>", "<img src='image.gif' alt='MyImage'>", "<img href='image.gif'>"], answer: 2 },
    { id: 15, category: "HTML", question: "What is the correct HTML for making a drop-down list?", options: ["<input type='list'>", "<list>", "<select>", "<input type='dropdown'>"], answer: 2 },
    { id: 16, category: "HTML", question: "Which HTML element defines navigation links?", options: ["<navigate>", "<nav>", "<bar>", "<links>"], answer: 1 },
    { id: 17, category: "HTML", question: "What does the <aside> element define?", options: ["A navigation bar", "Content aside from the page content", "The footer area", "A section block"], answer: 1 },
    { id: 18, category: "HTML", question: "Which HTML element is used to display a scalar measurement within a known range?", options: ["<gauge>", "<range>", "<measure>", "<meter>"], answer: 3 },
    { id: 19, category: "HTML", question: "In HTML, which attribute is used to specify an alternate text for an image?", options: ["title", "src", "alt", "longdesc"], answer: 2 },
    { id: 20, category: "HTML", question: "Which doctype is correct for HTML5?", options: ["<!DOCTYPE html>", "", "<!DOCTYPE HTML5>", "<doctype html>"], answer: 0 },
    { id: 21, category: "HTML", question: "Which HTML element is used to specify a footer for a document or section?", options: ["<bottom>", "<section>", "<foot>", "<footer>"], answer: 3 },
    { id: 22, category: "HTML", question: "What is the correct HTML element for playing video files?", options: ["<media>", "<video>", "<movie>", "<play>"], answer: 1 },
    { id: 23, category: "HTML", question: "What is the correct HTML element for playing audio files?", options: ["<audio>", "<sound>", "<music>", "<voice>"], answer: 0 },
    { id: 24, category: "HTML", question: "Global attributes can be used on any HTML element.", options: ["True", "False"], answer: 0 },
    { id: 25, category: "HTML", question: "Which attribute specifies where to send the form-data when a form is submitted?", options: ["method", "action", "src", "name"], answer: 1 },

    // === CSS (Questions 26-50) ===
    { id: 26, category: "CSS", question: "What does CSS stand for?", options: ["Creative Style Sheets", "Cascading Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"], answer: 1 },
    { id: 27, category: "CSS", question: "What is the correct HTML for referring to an external style sheet?", options: ["<style src='mystyle.css'>", "<link rel='stylesheet' type='text/css' href='mystyle.css'>", "<stylesheet>mystyle.css</stylesheet>", "<link src='mystyle.css'>"], answer: 1 },
    { id: 28, category: "CSS", question: "Which HTML tag is used to define an internal style sheet?", options: ["<css>", "<script>", "<style>", "<inline>"], answer: 2 },
    { id: 29, category: "CSS", question: "Which HTML attribute is used to define inline styles?", options: ["styles", "font", "style", "class"], answer: 2 },
    { id: 30, category: "CSS", question: "Which is the correct CSS syntax?", options: ["body {color: black;}", "{body;color:black;}", "body:color=black;", "{body:color=black;}"], answer: 0 },
    { id: 31, category: "CSS", question: "How do you insert a comment in a CSS file?", options: ["// this is a comment", "' this is a comment", "/* this is a comment */", "// this is a comment //"], answer: 2 },
    { id: 32, category: "CSS", question: "Which property is used to change the background color?", options: ["color", "bgcolor", "background-color", "background"], answer: 2 },
    { id: 33, category: "CSS", question: "How do you add a background color for all <h1> elements?", options: ["h1 {background-color:#FFFFFF;}", "h1.all {background-color:#FFFFFF;}", "all.h1 {background-color:#FFFFFF;}", "h1 {bg: #FFFFFF;}"], answer: 0 },
    { id: 34, category: "CSS", question: "Which CSS property is used to change the text color of an element?", options: ["text-color", "fgcolor", "color", "font-color"], answer: 2 },
    { id: 35, category: "CSS", question: "Which CSS property controls the text size?", options: ["font-style", "text-size", "font-size", "text-style"], answer: 2 },
    { id: 36, category: "CSS", question: "What is the correct CSS syntax for making all the <p> elements bold?", options: ["p {font-weight:bold;}", "p {text-size:bold;}", "<p style='font-size:bold;'>", "p {font:bold;}"], answer: 0 },
    { id: 37, category: "CSS", question: "How do you display hyperlinks without an underline?", options: ["a {text-decoration:none;}", "a {underline:none;}", "a {text-decoration:no-underline;}", "a {clear:underline;}"], answer: 0 },
    { id: 38, category: "CSS", question: "How do you make each word in a text start with a capital letter?", options: ["text-transform:capitalize", "text-transform:uppercase", "You cannot do that with CSS", "font-style:capitalize"], answer: 0 },
    { id: 39, category: "CSS", question: "Which font property defines a font family name?", options: ["font-type", "font-family", "font-name", "font-style"], answer: 1 },
    { id: 40, category: "CSS", question: "How do you make the text bold?", options: ["font:bold;", "font-weight:bold;", "style:bold;", "text-weight:bold;"], answer: 1 },
    { id: 41, category: "CSS", question: "How do you display a border like this: Top border=10px, Bottom=5px, Left=20px, Right=1px?", options: ["border-width:10px 1px 5px 20px;", "border-width:10px 20px 5px 1px;", "border-width:10px 5px 20px 1px;", "border-width:5px 20px 10px 1px;"], answer: 0 },
    { id: 42, category: "CSS", question: "Which property is used to change the left margin of an element?", options: ["margin-left", "padding-left", "indent", "left-margin"], answer: 0 },
    { id: 43, category: "CSS", question: "When using the padding property; are you allowed to use negative values?", options: ["Yes", "No"], answer: 1 },
    { id: 44, category: "CSS", question: "How do you make a list that lists its items with square bullets?", options: ["list-style-type: square;", "list-type: square;", "bullet-type: square;", "list: square;"], answer: 0 },
    { id: 45, category: "CSS", question: "How do you select an element with id 'demo'?", options: [".demo", "#demo", "*demo", "demo"], answer: 1 },
    { id: 46, category: "CSS", question: "How do you select elements with class name 'test'?", options: ["*test", "#test", "test", ".test"], answer: 3 },
    { id: 47, category: "CSS", question: "How do you select all p elements inside a div element?", options: ["div p", "div.p", "div + p", "div > p"], answer: 0 },
    { id: 48, open: "CSS", question: "What is the default value of the position property?", options: ["relative", "fixed", "absolute", "static"], answer: 3 },
    { id: 49, category: "CSS", question: "Which property is used to overlay elements sequentially on top of each other?", options: ["z-index", "layers", "stack", "position"], answer: 0 },
    { id: 50, category: "CSS", question: "Which CSS property is used to make content responsive using grids?", options: ["display: flex", "display: grid", "display: block", "float: left"], answer: 1 },

    // === JavaScript (Questions 51-75) ===
    { id: 51, category: "JavaScript", question: "Inside which HTML element do we put the JavaScript?", options: ["<js>", "<scripting>", "<script>", "<javascript>"], answer: 2 },
    { id: 52, category: "JavaScript", question: "What is the correct syntax to target an element by ID?", options: ["document.getElement('p')", "document.getElementById('demo')", "#demo", "document.getElementsName('demo')"], answer: 1 },
    { id: 53, category: "JavaScript", question: "Where is the correct place to insert JavaScript?", options: ["Both the <head> and <body> sections", "The <body> section exclusively", "The <head> section exclusively", "None of these"], answer: 0 },
    { id: 54, category: "JavaScript", question: "How do you write 'Hello World' in an alert box?", options: ["msg('Hello World');", "alertBox('Hello World');", "msgBox('Hello World');", "alert('Hello World');"], answer: 3 },
    { id: 55, category: "JavaScript", question: "How do you create a function in JavaScript?", options: ["function myFunction()", "function:myFunction()", "function = myFunction()", "new function()"], answer: 0 },
    { id: 56, category: "JavaScript", question: "How do you call a function named 'myFunction'?", options: ["call function myFunction()", "myFunction()", "call myFunction()", "execute myFunction()"], answer: 1 },
    { id: 57, category: "JavaScript", question: "How to write an IF statement in JavaScript?", options: ["if i = 5 then", "if i == 5 then", "if (i == 5)", "if i = 5"], answer: 2 },
    { id: 58, category: "JavaScript", question: "How to write an IF statement for executing code if 'i' is NOT equal to 5?", options: ["if (i <> 5)", "if i != 5 then", "if (i != 5)", "if i <> 5 then"], answer: 2 },
    { id: 59, category: "JavaScript", question: "How does a WHILE loop start?", options: ["while (i <= 10)", "while i = 1 to 10", "while (i <= 10; i++)", "while i <= 10"], answer: 0 },
    { id: 60, category: "JavaScript", question: "How does a FOR loop start?", options: ["for (i = 0; i <= 5)", "for (i = 0; i <= 5; i++)", "for i = 1 to 5", "for (i <= 5; i++)"], answer: 1 },
    { id: 61, category: "JavaScript", question: "How can you add a single-line comment in JavaScript?", options: ["' This is a comment", "// This is a comment", "", "/* This is a comment"], answer: 1 },
    { id: 62, category: "JavaScript", question: "What is the correct way to write a JavaScript array?", options: ["var colors = (1:'red', 2:'green')", "var colors = ['red', 'green', 'blue']", "var colors = 'red', 'green', 'blue'", "var colors = 1 = ('red'), 2 = ('green')"], answer: 1 },
    { id: 63, category: "JavaScript", question: "How do you round the number 7.25, to the nearest integer?", options: ["Math.round(7.25)", "rnd(7.25)", "Math.rnd(7.25)", "round(7.25)"], answer: 0 },
    { id: 64, category: "JavaScript", question: "How do you find the highest number of x and y?", options: ["Math.max(x, y)", "ceil(x, y)", "Math.highest(x, y)", "top(x, y)"], answer: 0 },
    { id: 65, category: "JavaScript", question: "Which event occurs when the user clicks on an HTML element?", options: ["onmouseover", "onchange", "onclick", "onmouseclick"], answer: 2 },
    { id: 66, category: "JavaScript", question: "How do you declare a JavaScript variable?", options: ["v carName;", "var carName;", "variable carName;", "string carName;"], answer: 1 },
    { id: 67, category: "JavaScript", question: "Which operator is used to assign a value to a variable?", options: ["*", "-", "=", "x"], answer: 2 },
    { id: 68, category: "JavaScript", question: "What will the following code return: Boolean(10 > 9)?", options: ["true", "false", "NaN", "undefined"], answer: 0 },
    { id: 69, category: "JavaScript", question: "Is JavaScript case-sensitive?", options: ["Yes", "No"], answer: 0 },
    { id: 70, category: "JavaScript", question: "Which built-in method returns the length of a string?", options: ["length()", "size()", "index", "length"], answer: 3 },
    { id: 71, category: "JavaScript", question: "Which keyword is used to declare a block-scoped local variable?", options: ["var", "let", "global", "set"], answer: 1 },
    { id: 72, category: "JavaScript", question: "What does NaN stand for?", options: ["New and Null", "Number and Null", "Not a Number", "Null and Negative"], answer: 2 },
    { id: 73, category: "JavaScript", question: "Which method adds a new element to the end of an array?", options: ["pop()", "push()", "shift()", "unshift()"], answer: 1 },
    { id: 74, category: "JavaScript", question: "How do you open a confirmation dialogue box?", options: ["alert()", "msg()", "confirm()", "prompt()"], answer: 2 },
    { id: 75, category: "JavaScript", question: "Which symbol is used for strict equality comparison?", options: ["==", "=", "===", "!="], answer: 2 },

    // === Python (Questions 76-100) ===
    { id: 76, category: "Python", question: "What is the correct syntax to output 'Hello World' in Python?", options: ["p('Hello World')", "print('Hello World')", "echo('Hello World')", "printf('Hello World')"], answer: 1 },
    { id: 77, category: "Python", question: "How do you insert COMMENTS in Python code?", options: ["// This is a comment", "/* This is a comment */", "# This is a comment", ""], answer: 2 },
    { id: 78, category: "Python", question: "Which data type is NOT built-in in Python?", options: ["List", "Dictionary", "Tuple", "Array"], answer: 3 },
    { id: 79, category: "Python", question: "How do you create a variable with the numeric value 5?", options: ["x = 5", "x = int(5)", "Both of the above methods", "None of the above"], answer: 2 },
    { id: 80, category: "Python", question: "What is the correct file extension for Python files?", options: [".pt", ".py", ".pyt", ".python"], answer: 1 },
    { id: 81, category: "Python", question: "Is Python case-sensitive when dealing with identifiers?", options: ["Yes", "No"], answer: 0 },
    { id: 82, category: "Python", question: "What is the correct syntax to output the type of a variable in Python?", options: ["print(typeof(x))", "print(type(x))", "print(id(x))", "print(class(x))"], answer: 1 },
    { id: 83, category: "Python", question: "How do you create a function in Python?", options: ["function myFunction():", "def myFunction():", "create myFunction():", "void myFunction():"], answer: 1 },
    { id: 84, category: "Python", question: "What is the correct way to start a conditional 'if' statement in Python?", options: ["if x > y:", "if (x > y)", "if x > y then:", "if x > y then"], answer: 0 },
    { id: 85, category: "Python", question: "Which statement is used to stop a loop?", options: ["exit", "stop", "break", "return"], answer: 2 },
    { id: 86, category: "Python", question: "Which collections collection is ordered, changeable, and allows duplicate members?", options: ["LIST", "TUPLE", "SET", "DICTIONARY"], answer: 0 },
    { id: 87, category: "Python", question: "Which collection is ordered and UNCHANGEABLE?", options: ["List", "Set", "Dictionary", "Tuple"], answer: 3 },
    { id: 88, category: "Python", question: "How do you call a function named 'my_func' in Python?", options: ["call my_func()", "my_func()", "def my_func()", "execute my_func()"], answer: 1 },
    { id: 89, category: "Python", question: "Which operator is used to calculate the remainder of a division?", options: ["/", "%", "//", "div"], answer: 1 },
    { id: 90, category: "Python", question: "How do you check if an item exists within a list?", options: ["using the 'in' keyword", "using the 'contains' method", "using the 'exist' function", "using find()"], answer: 0 },
    { id: 91, category: "Python", question: "What is the default index start position for list elements?", options: ["1", "-1", "0", "Any number"], answer: 2 },
    { id: 92, category: "Python", question: "Which keyword is used to handle exceptions in Python?", options: ["catch", "except", "try", "error"], answer: 1 },
    { id: 93, category: "Python", question: "How do you start a multi-line comment block in Python?", options: ["/* ... */", "''' ... '''", "### ... ###", "// ... //"], answer: 1 },
    { id: 94, category: "Python", question: "What does the len() function do?", options: ["Returns string in lowercase", "Returns memory allocation limit", "Returns the number of items in an object", "Generates a linear equation array"], answer: 2 },
    { id: 95, category: "Python", question: "Which operator is used for exponentiation (power calculation)?", options: ["^", "**", "pow", "xs"], answer: 1 },
    { id: 96, category: "Python", question: "How do you add an element to the end of a list?", options: ["add()", "insert()", "append()", "push()"], answer: 2 },
    { id: 97, category: "Python", question: "What is the output of print(2 * 3 ** 2)?", options: ["36", "18", "64", "12"], answer: 1 },
    { id: 98, category: "Python", question: "Which method removes all elements from a dictionary?", options: ["remove()", "clear()", "delete()", "flush()"], answer: 1 },
    { id: 99, category: "Python", question: "What is the dynamic output of 'hello'[1:4] string slicing?", options: ["ell", "hell", "ello", "el"], answer: 0 },
    { id: 100, category: "Python", question: "Which keyword is used to create a class in Python?", options: ["className", "struct", "object", "class"], answer: 3 }
];